app = "platform-work-sample-codeserver"

kill_signal  = "SIGINT"
kill_timeout = 5
processes    = []

[env]

[mounts]
source      = "data"
destination = "/root"

[experimental]
allowed_public_ports = []
auto_rollback        = true

[[services]]
internal_port = 2222
protocol      = "tcp"
script_checks = []

  [[services.ports]]
  port = 2222
